services:
  frontend:
    build: ./frontend
    command: npm start
    container_name: template_frontend
    environment:
      - PORT=8000
      - WDS_SOCKET_HOST=127.0.0.1
    # Porta externa 8085, Porta interna 8000
    ports:
      - 8085:8000
    restart: unless-stopped
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  backend:
    build: ./backend
    command: ["flask", "run", "--host=0.0.0.0"]
    container_name: template_backend
    environment:
      - PORT=5000
      - FLASK_APP=app.py
    # Porta externa 5015, Porta interna 5000
    ports:
      - 5015:5000
    restart: unless-stopped
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    container_name: template_postgres
    # Porta externa 2345, Porta interna 5432
    ports:
      - 2345:5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=keypass
      - POSTGRES_DB=templatedb
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
    driver: local
